'''
Created on Jan 16, 2015

@author: Dan
'''

title = input("Input the title: ")
price = input("Input the price: ")
imgsrc = input("Input the imgsrc (no quotation marks): ")
tag_url = input("Input the tag_url: ")
deal_number = input("Input the deal number, i.e. 00XX: ")

print('')
print('')
print('<!-- new panel item for a deal -->')
print('<a href="deals/deal' + deal_number + '.html">')
print('    <div class="panel panel-default panel-link panel-custom-border-color">')
print('        <div class="panel-body">')
print('            <div class="row vertical-align">')
print('                <div class="col-xs-3">')
print('                    <img src="' + imgsrc + '" class="img-thumbnail img-responsive">')
print('                </div>')
print('                <div class="col-xs-9">')
print('                    <h3 class="text-center">' + title + ' --- ' + price + '</h3>')
print('                </div>')
print('            </div>')
print('        </div>')
print('    </div>')
print('</a>')

fo = open("deal" + str(deal_number) + ".html", "a")

fo.write('')
fo.write('')
fo.write('<!-- template for adding another deal PAGE-->')
fo.write('')
fo.write('<!DOCTYPE html>')
fo.write('<html>')
fo.write('<head>')
fo.write('    <title>' + title + '</title>')
fo.write('    <link rel="shortcut icon" href="../img/favicon.ico">')
fo.write('    <meta name="viewport" content="width=device-width, initial-scale=1.0">')
fo.write('')
fo.write('    <link rel="stylesheet" type="text/css" href="../css/bootstrap.min.css">')
fo.write('    <link rel="stylesheet" type="text/css" href="../css/styles.css">')
fo.write('    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js">')
fo.write('    </script>')
fo.write('</head>')
fo.write('<body>')
fo.write('    <nav class="navbar navbar-inverse navbar-static-top navbar-fixed-top" role="navigation">')
fo.write('        <div class="container">')
fo.write('            <div class="navbar-header">')
fo.write('                <a class="navbar-brand" id="brand-text" href="../index.html">')
fo.write('                    D e a l &nbsp;&nbsp; G i r a f f e')
fo.write('                </a>')
fo.write('                <button class="navbar-toggle" data-toggle="collapse" data-target=".navHeaderCollapse">')
fo.write('                <span class="icon-bar"></span>')
fo.write('                <span class="icon-bar"></span>')
fo.write('                <span class="icon-bar"></span>')
fo.write('                </button>')
fo.write('            </div>')
fo.write('            <div class="collapse navbar-collapse navHeaderCollapse">')
fo.write('                <ul class="nav navbar-nav navbar-right">')
fo.write('                    <li><a href="../index.html">Home</a></li>')
fo.write('                    <li><a href="../blog.html">Blog</a></li>')
fo.write('                    <li><a href="https://twitter.com/Deal_Giraffe">Twitter</a></li>')
fo.write('                    <li><a href="#contact" data-toggle="modal">Contact</a></li>')
fo.write('                </ul>')
fo.write('            </div>')
fo.write('        </div>')
fo.write('    </nav>')
fo.write('    <div class="row">')
fo.write('        <div class="col-sm-10 col-sm-offset-1 col-lg-8 col-lg-offset-2">')
fo.write('            <!-- top of page panel info thing -->')
fo.write('            <div class="panel panel-default panel-custom-border-color">')
fo.write('                <div class="panel-body text-center top-panel">')
fo.write('                    <strong>One of the hottest deals found today!</strong>')
fo.write('                </div>')
fo.write('            </div>')
fo.write('            <!--object title -->')
fo.write('            <div class="text-center">')
fo.write('                <a href="' + tag_url + '"><h2>' + title + ' --- ' + price + '</h2></a>')
fo.write('            </div>')
fo.write('            <!-- jumbotron with the circle image inside it -->')
fo.write('            <div class="jumbotron text-center jumbotron-item-page center-block">')
fo.write('                <a href="' + tag_url + '">')
fo.write('                    <img class="img-responsive img-thumbnail img-item" src="' + imgsrc + '">')
fo.write('                </a>')
fo.write('            </div>')
fo.write('            <!--panel containing info about the deal itself -->')
fo.write('            <div class="panel panel-info panel-info-custom">')
fo.write('                <div class="panel-heading">')
fo.write('                    <h3 class="panel-title"><strong>Info</strong></h3>')
fo.write('                </div>')
fo.write('                <div class="panel-body">')
fo.write('                    <p> - Product link(s)</p>')
fo.write('                    <ul>')
fo.write('                    <a href="' + tag_url + '"><li>Amazon - ' + title + '</li></a>')
fo.write('                    </ul>')
fo.write('                    <p> - </p>')
fo.write('                    <p> - </p>')
fo.write('                    <p> - </p>')
fo.write('                </div>')
fo.write('            </div>')
fo.write('        </div>')
fo.write('    </div>')
fo.write('    <div class="text-center center-block">  ')
fo.write('        <script type=\'text/javascript\'>')
fo.write('         amzn_assoc_ad_type = \'banner\';')
fo.write('         amzn_assoc_tracking_id = \'dealgira-20\';')
fo.write('         amzn_assoc_marketplace = \'amazon\';')
fo.write('         amzn_assoc_region = \'US\';')
fo.write('         amzn_assoc_placement = \'assoc_banner_placement_default\';')
fo.write('         amzn_assoc_linkid = \'AJBNQOSLWPK2CKPF\';')
fo.write('         amzn_assoc_campaigns = \'nyny2015\';')
fo.write('         amzn_assoc_p = \'48\';')
fo.write('         amzn_assoc_banner_type = \'category\';')
fo.write('         amzn_assoc_isresponsive = \'false\';')
fo.write('         amzn_assoc_banner_id = \'0GS3JFD8HQ2WDP90ZV02\';')
fo.write('         amzn_assoc_width = \'728\';')
fo.write('         amzn_assoc_height = \'90\';')
fo.write('        </script>')
fo.write('        <script src=\'//z-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&Operation=GetScript&ID=OneJS&WS=1\'></script>')
fo.write('    </div>')
fo.write('    <div class="modal fade" id="contact" role="dialog">')
fo.write('        <div class="modal-dialog">')
fo.write('            <div class="modal-content">')
fo.write('                <form class="form-horizontal">')
fo.write('                    <div class="modal-header">')
fo.write('                        <h4>Contact Deal Giraffe</h4>')
fo.write('                    </div>')
fo.write('                    <div class="modal-body">')
fo.write('                        <p>Contacting Deal Giraffe is simple. Just email dealgiraffe@gmail.com and I will get back to you almost right away. (Hopefully) If not then definitely expect something within 12 hours or so.</p>')
fo.write('                    </div>')
fo.write('                    <div class="modal-footer">')
fo.write('                        <a href="#" class="btn btn-default" data-dismiss="modal">Close</a>')
fo.write('                    </div>')
fo.write('                </form>')
fo.write('            </div>')
fo.write('        </div>')
fo.write('    </div>')
fo.write('    <script type="text/javascript" src="../js/bootstrap.js"></script>')
fo.write('</body>')
fo.write('</html>')









